config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :movies

      root to: "users#index"
    end
  get 'watchlists/update'
  resources :trailers
  resources :create_trailers
  resources :movies
  resources :subscribers
  put '/subscribers/:id', to: 'subscribers#update', as: 'subscriber_update'
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:  'movies#index'
end

app/controllers/admin/movies_controller.rb
module Admin
  class MoviesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]  
  before_action :check_user
  
  # GET /movies or /movies.json
  def index
    @trailers = Trailer.all
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
    @watchlist_exists = Watchlist.where(movie: @movie, user: current_user) == [] ? false : true
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:movie_id, :title, :release_date, :backdrop_path, :poster_path, :overview, :average_vote, :buget, :tegline, :tegline)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Prijava',new_user_session_path if !user_signed_in? %>
<%= link_to 'Odjava',destroy_user_session_path, method: :delete if user_signed_in? %>
<main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">My watchlist</h1>
          <%= if user_signed_in?
              current_user.watchlists.each do |wachlist|
                wachlist.movie.title
              end
          end%>
          <%= if !user_signed_in?
              link_to 'Create an account to get a watchlist', new_user_registration_url
          end%>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <h1 style="margin:0 auto; text-align:center;">Upcoming movies</h1>
        <div class="container">

          <div class="row">
            <% @trailers.each do |trailer| %>

              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                  <iframe style="height: 225px; width: 100%; display: block;"  class="card-img-top" src='https://www.youtube.com/embed/<%= trailer.videoId %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen  class="tra"></iframe>
                </div>
              </div>
            <% end %>
          </div>
          <br>
          <div class="row">
            <h1 style="margin:0 auto; text-align:center;">Top movies</h1>
            <% @movies.each do |movie| %>
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                  <%= link_to (image_tag 'https://image.tmdb.org/t/p/w300/' + movie.poster_path, :style =>"width: 100%;" ), movie_path(movie.id), :class=> "card-img-top", :style=>"height: 650px; width: 100%; display: block;" %>
                  <div class="card-body">
                    <h3 class="card-text"><%= movie.title %></h3>
                    <p class="card-text">Release date: <%= movie.release_date %></p>
                    <div class="d-flex justify-content-between align-items-center">
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    </main>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="back">
<%= link_to 'Back', movies_path %>
</div>

<div class="slika2">
<%= image_tag 'https://image.tmdb.org/t/p/w1280/' + @movie.backdrop_path %>
</div>

<div class="naslov2">
<h2><%= @movie.title %></h2>
</div>

<div class="podatki">
Average vote:
<%= @movie.average_vote %>
<%= @movie.overview %>
Release Date: <%= (@movie.release_date).to_time.strftime(' %b %d %Y') %>
Duration: <%= @movie.runtime %>m
<div>
<%= link_to watchlist_text, watchlists_update_path(movie: @movie), id:'wachlist_link', remote: true %>

</div>

</div>