config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :movies

      root to: "users#index"
    end
  get 'watchlists/update'
  resources :trailers
  resources :create_trailers
  resources :movies
  resources :subscribers
  put '/subscribers/:id', to: 'subscribers#update', as: 'subscriber_update'
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:  'movies#index'
end

app/models/trailer.rb
class Trailer < ApplicationRecord
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  before_action :set_trailer, only: %i[ show edit update destroy ]

  # GET /trailers or /trailers.json
  def index
    @trailers = Trailer.all
  end

  # GET /trailers/1 or /trailers/1.json
  def show
    if user_signed_in?
      if !current_user.subscribed
        redirect_to new_subscriber_path
      end
    end
  end

  # GET /trailers/new
  def new
    @trailer = Trailer.new
  end

  # GET /trailers/1/edit
  def edit
  end

  # POST /trailers or /trailers.json
  def create
    @trailer = Trailer.new(trailer_params)

    respond_to do |format|
      if @trailer.save
        format.html { redirect_to @trailer, notice: "Trailer was successfully created." }
        format.json { render :show, status: :created, location: @trailer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trailers/1 or /trailers/1.json
  def update
    respond_to do |format|
      if @trailer.update(trailer_params)
        format.html { redirect_to @trailer, notice: "Trailer was successfully updated." }
        format.json { render :show, status: :ok, location: @trailer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trailers/1 or /trailers/1.json
  def destroy
    @trailer.destroy
    respond_to do |format|
      format.html { redirect_to trailers_url, notice: "Trailer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trailer
      @trailer = Trailer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trailer_params
      params.require(:trailer).permit(:videoID)
    end
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/trailers/_form.html.erb
<%= form_with(model: trailer) do |form| %>
  <% if trailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trailer.errors.count, "error") %> prohibited this trailer from being saved:</h2>

      <ul>
        <% trailer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :videoID %>
    <%= form.text_field :videoID %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trailers/edit.html.erb
<h1>Editing Trailer</h1>

<%= render 'form', trailer: @trailer %>

<%= link_to 'Show', @trailer %> |
<%= link_to 'Back', trailers_path %>

app/views/trailers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trailers</h1>

<table>
  <thead>
    <tr>
      <th>Videoid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trailers.each do |trailer| %>
      <tr>
        <td><%= trailer.videoID %></td>
        <td><%= link_to 'Show', trailer %></td>
        <td><%= link_to 'Edit', edit_trailer_path(trailer) %></td>
        <td><%= link_to 'Destroy', trailer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trailer', new_trailer_path %>

app/views/trailers/new.html.erb
<h1>New Trailer</h1>

<%= render 'form', trailer: @trailer %>

<%= link_to 'Back', trailers_path %>

app/views/trailers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Videoid:</strong>
  <%= @trailer.videoID %>
</p>

<%= link_to 'Edit', edit_trailer_path(@trailer) %> |
<%= link_to 'Back', trailers_path %>