config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :movies

      root to: "users#index"
    end
  get 'watchlists/update'
  resources :trailers
  resources :create_trailers
  resources :movies
  resources :subscribers
  put '/subscribers/:id', to: 'subscribers#update', as: 'subscriber_update'
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:  'movies#index'
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  before_action :authenticate_user!
  require "stripe"
  
  def show
  end

  def new
    if user_signed_in? && current_user.subscribed?
      redirect_to root_path, notice: "You are already a subscriber!"
    end
  end

  def update
    Stripe.api_key = ENV["STRIPE_SECRET_KEY"]

    plan_id = 'prod_JIKWwiwuJFfiJj'
    token = params[:stripeToken]

    customer = if current_user.stripeid?
                Stripe::Customer.retrieve(current_user.stripeid)
               else
                Stripe::Customer.create(email: current_user.email, source: token)
              end

    #subscription = customer.subscriptions.create(plan: plan.id)

    options = {
      stripeid: customer.id,
      subscribed: true
    }

    #options.merge!(
    #  card_last4: params[:user][:card_last4],
    #  card_exp_month: params[:user][:card_exp_month],
    #  card_exp_year: params[:user][:card_exp_year],
    #  card_type: params[:user][:card_type]
    #) if params[:user][:card_last4]

    current_user.update(options)

    redirect_to root_path, notice: "Your subscription was setup successfully!"
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripeid: nil, subscribed: nil)

    redirect_to root_path, notice: "Your subscription has been canceled."
  end

  private

    def redirect_to_signup
      if !user_signed_in?
        session["user_return_to"] = new_subscription_path
        redirect_to new_user_registration_path
      end
    end

end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_tag subscriber_update_path(1), method: :put do %>


<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>"
          data-description="A month's subscription"
          data-amount="1200"></script><span> 12€ per month, cancel at any time.</span>

<% end %>

app/views/subscribers/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 panel panel-default form-style">
            <div class="panel-body">
                <h2>Final Signup Step</h2>
                <h4>This is the final step to give you full access to MovieShow app.</h4>
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>